language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
script: rake && rake auto_install_spec
deploy:
  provider: rubygems
  api_key:
    secure: NBv6PVLLkJuEmRTNalpotHhNTbQ1GZfccxUYBX++OcOd9g6EMY14kWoSOHUd3cmpmrg0+87PpkFt6PNIDf+cp+5eLQTS4BsqgxELattZeM14hK+5aLK3TZWhzBXKHSCw0e/VIp11pN2vzJezeDeI4pRvNHYdSBvLeSLnaouZCDDGTClZhLjNSwpTTczUD+KxuaOGXecAN5ha3r1OvLHzujiwVeqS7fNPOUccEZlZpAaV9sHmUKb8+iv2RQae9gmgQ4ABfZoQao6vjjbeg9YOoup2mGsQuSNH4iGM+NFWCauGbCq1gCLuYb/idvgLOrgGUOmos76IxduK/x7AWBfQAOrDoqx05YMb50IDTcocFOLiN0YCgo0LkrXcMRym++xrOLClZCTUquOVQG1QbR3TuId0lyLGoIvGThzTTP6IHad43gilE4q976Pejftx3uHpjkIVO45pvlcFTvRO+78YFdHFvU0Nqf0/L7cBNR53U5xFBH83arXsQHFa+yVWKfbLSuIJ0421P+2fcNMh1y9310F+LnVPJsbAiXxLsfHWAX/NE0J/HYOZvnFki6uNzRKyyCqrZXZBhForZXoUXBi8M++W16PFimK5YM7j3ZxOy8oPyvB/d1vZlspxuyWpF2MqgXe5USzUwzLaFX34WlTqHmYePXRvoffUHzwbibgpNmc=
  gem: faraday-honeycomb
  on:
    tags: true
    repo: honeycombio/faraday-honeycomb
    ruby: '2.4'
